# Generated by Django 5.1.5 on 2025-01-17 12:27

import django.db.models.deletion
import django.utils.timezone
import syzygy.models.research_views
import syzygy.models.timeline
import syzygy.models.triage
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentInteraction",
            fields=[
                (
                    "id",
                    models.CharField(max_length=26, primary_key=True, serialize=False),
                ),
                ("agent_type", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=100)),
                ("provider", models.CharField(max_length=50)),
                ("operation", models.CharField(max_length=100)),
                ("prompt_tokens", models.IntegerField()),
                ("completion_tokens", models.IntegerField()),
                ("latency_ms", models.IntegerField()),
                ("success", models.BooleanField()),
                ("error_type", models.CharField(blank=True, max_length=50, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("cost_millicents", models.IntegerField()),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.CharField(max_length=26)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "agent_interactions",
                "indexes": [
                    models.Index(fields=["agent_type"], name="interaction_agent_idx"),
                    models.Index(fields=["model_name"], name="interaction_model_idx"),
                    models.Index(fields=["created_at"], name="interaction_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=syzygy.models.timeline.generate_uuid,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("preferences", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "clients",
                "indexes": [models.Index(fields=["email"], name="client_email_idx")],
            },
        ),
        migrations.CreateModel(
            name="ResearchIteration",
            fields=[
                (
                    "id",
                    models.CharField(max_length=26, primary_key=True, serialize=False),
                ),
                ("iteration_type", models.CharField(max_length=50)),
                ("source_count", models.IntegerField(null=True)),
                ("date_range", models.CharField(max_length=50)),
                ("summary", models.TextField()),
                ("key_changes", models.JSONField(default=dict)),
                ("risk_factors", models.JSONField(default=dict)),
                ("opportunities", models.JSONField(default=dict)),
                ("confidence_metrics", models.JSONField(default=dict)),
                ("status", models.CharField(max_length=50)),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "reviewed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("prompt_template", models.CharField(max_length=100)),
                ("model_version", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_iteration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="syzygy.researchiteration",
                    ),
                ),
            ],
            options={
                "db_table": "research_iterations",
            },
        ),
        migrations.CreateModel(
            name="ResponseDraft",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=syzygy.models.triage.generate_uuid,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_email", models.TextField(default="")),
                ("email_subject", models.CharField(default="", max_length=255)),
                ("draft_content", models.TextField(default="")),
                ("status", models.CharField(default="draft", max_length=50)),
                ("priority", models.IntegerField(default=0)),
                ("context_notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syzygy.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Response Draft",
                "verbose_name_plural": "Response Drafts",
                "db_table": "response_drafts",
            },
        ),
        migrations.CreateModel(
            name="ProcessingMetrics",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=syzygy.models.triage.generate_uuid,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("processing_time_ms", models.IntegerField(default=0)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("complexity_score", models.FloatField(default=0.0)),
                ("sentiment_score", models.FloatField(default=0.0)),
                ("topic_scores", models.JSONField(default=dict)),
                ("model_metrics", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "response_draft",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syzygy.responsedraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Metric",
                "verbose_name_plural": "Processing Metrics",
                "db_table": "processing_metrics",
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=syzygy.models.timeline.generate_uuid,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(default="general", max_length=50),
                ),
                ("content", models.TextField(default="")),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syzygy.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcript",
                "verbose_name_plural": "Transcripts",
                "db_table": "transcripts",
            },
        ),
        migrations.CreateModel(
            name="TranscriptAnalysis",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=syzygy.models.timeline.generate_uuid,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summary", models.TextField(default="")),
                ("key_points", models.JSONField(default=list)),
                ("sentiment", models.FloatField(default=0.0)),
                ("topics", models.JSONField(default=list)),
                ("entities", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transcript",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syzygy.transcript",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcript Analysis",
                "verbose_name_plural": "Transcript Analyses",
                "db_table": "transcript_analyses",
            },
        ),
        migrations.CreateModel(
            name="Universe",
            fields=[
                (
                    "id",
                    models.CharField(max_length=26, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("ticker", models.CharField(max_length=20, unique=True)),
                ("isin", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "openfigi",
                    models.CharField(
                        blank=True,
                        help_text="OpenFIGI identifier",
                        max_length=12,
                        null=True,
                        unique=True,
                        verbose_name="OpenFIGI",
                    ),
                ),
                ("security_type", models.CharField(max_length=50)),
                ("market_cap", models.FloatField(blank=True, null=True)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Universe",
                "verbose_name_plural": "Universe",
                "db_table": "universe",
                "indexes": [
                    models.Index(fields=["ticker"], name="universe_ticker_idx"),
                    models.Index(fields=["openfigi"], name="universe_figi_idx"),
                    models.Index(fields=["security_type"], name="universe_type_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="transcript",
            name="security",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="syzygy.universe",
            ),
        ),
        migrations.CreateModel(
            name="TickHistory",
            fields=[
                (
                    "id",
                    models.CharField(max_length=26, primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("old_tick", models.IntegerField(null=True)),
                ("new_tick", models.IntegerField()),
                ("note", models.TextField(blank=True)),
                ("updated_by", models.CharField(max_length=255)),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syzygy.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tick History",
                "verbose_name_plural": "Tick History",
                "db_table": "tick_history",
            },
        ),
        migrations.CreateModel(
            name="ResearchSources",
            fields=[
                (
                    "id",
                    models.CharField(max_length=26, primary_key=True, serialize=False),
                ),
                ("url", models.URLField(max_length=2048)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("snippet", models.TextField(blank=True)),
                ("source_type", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syzygy.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Source",
                "verbose_name_plural": "Research Sources",
                "db_table": "research_sources",
            },
        ),
        migrations.CreateModel(
            name="ResearchResults",
            fields=[
                (
                    "id",
                    models.CharField(max_length=26, primary_key=True, serialize=False),
                ),
                ("summary", models.TextField()),
                ("risk_score", models.IntegerField()),
                ("confidence_score", models.IntegerField()),
                ("recommendation", models.CharField(max_length=50)),
                ("structured_data", models.JSONField(default=dict)),
                ("raw_results", models.JSONField(default=dict)),
                ("search_queries", models.JSONField(default=dict)),
                ("source_date_range", models.CharField(max_length=50)),
                ("total_sources", models.IntegerField()),
                ("source_categories", models.JSONField(default=dict)),
                (
                    "first_analyzed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("meta_info", models.JSONField(default=dict)),
                (
                    "last_iteration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="syzygy.researchiteration",
                    ),
                ),
                (
                    "security",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syzygy.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Result",
                "verbose_name_plural": "Research Results",
                "db_table": "research_results",
            },
        ),
        migrations.AddField(
            model_name="researchiteration",
            name="security",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="syzygy.universe",
            ),
        ),
        migrations.CreateModel(
            name="MentalModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=syzygy.models.research_views.generate_uuid,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("description", models.TextField(default="")),
                ("key_components", models.JSONField(default=dict)),
                ("relationships", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "security",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syzygy.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mental Model",
                "verbose_name_plural": "Mental Models",
                "db_table": "mental_models",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeReference",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=syzygy.models.research_views.generate_uuid,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("content", models.TextField(default="")),
                ("source_url", models.URLField(blank=True, max_length=2048, null=True)),
                ("source_type", models.CharField(default="general", max_length=50)),
                ("confidence", models.IntegerField(default=0)),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mental_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syzygy.mentalmodel",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syzygy.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Reference",
                "verbose_name_plural": "Knowledge References",
                "db_table": "knowledge_references",
            },
        ),
        migrations.CreateModel(
            name="Exclusion",
            fields=[
                (
                    "id",
                    models.CharField(max_length=26, primary_key=True, serialize=False),
                ),
                ("category", models.CharField(max_length=50)),
                ("criteria", models.CharField(max_length=100)),
                (
                    "concerned_groups",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("decision", models.CharField(max_length=50)),
                (
                    "excluded_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_historical", models.BooleanField(default=False)),
                (
                    "excluded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syzygy.universe",
                    ),
                ),
            ],
            options={
                "db_table": "exclusions",
            },
        ),
        migrations.CreateModel(
            name="ContentReference",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=syzygy.models.research_views.generate_uuid,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content_type", models.CharField(default="general", max_length=50)),
                (
                    "content_id",
                    models.CharField(
                        default=syzygy.models.research_views.generate_uuid,
                        max_length=26,
                    ),
                ),
                ("relevance_score", models.FloatField(default=0.0)),
                ("context", models.TextField(default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "knowledge_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syzygy.knowledgereference",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syzygy.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Reference",
                "verbose_name_plural": "Content References",
                "db_table": "content_references",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=syzygy.models.timeline.generate_uuid,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("activity_type", models.CharField(default="general", max_length=50)),
                ("description", models.TextField(default="")),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syzygy.client",
                    ),
                ),
                (
                    "related_security",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="syzygy.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "db_table": "activities",
            },
        ),
        migrations.AddIndex(
            model_name="responsedraft",
            index=models.Index(fields=["client"], name="draft_client_idx"),
        ),
        migrations.AddIndex(
            model_name="responsedraft",
            index=models.Index(fields=["status"], name="draft_status_idx"),
        ),
        migrations.AddIndex(
            model_name="responsedraft",
            index=models.Index(fields=["priority"], name="draft_priority_idx"),
        ),
        migrations.AddIndex(
            model_name="responsedraft",
            index=models.Index(fields=["created_at"], name="draft_created_idx"),
        ),
        migrations.AddIndex(
            model_name="processingmetrics",
            index=models.Index(fields=["response_draft"], name="metrics_draft_idx"),
        ),
        migrations.AddIndex(
            model_name="processingmetrics",
            index=models.Index(
                fields=["confidence_score", "complexity_score"],
                name="metrics_scores_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transcriptanalysis",
            index=models.Index(fields=["transcript"], name="analysis_transcript_idx"),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(fields=["client"], name="transcript_client_idx"),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(fields=["security"], name="transcript_security_idx"),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(fields=["created_at"], name="transcript_date_idx"),
        ),
        migrations.AddIndex(
            model_name="tickhistory",
            index=models.Index(
                fields=["security", "date"],
                name="tick_security_date_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tickhistory",
            unique_together={("security", "date")},
        ),
        migrations.AddIndex(
            model_name="researchsources",
            index=models.Index(
                fields=["security", "source_type"],
                name="sources_security_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="researchsources",
            index=models.Index(fields=["category"], name="sources_category_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="researchsources",
            unique_together={("security", "url")},
        ),
        migrations.AddIndex(
            model_name="researchresults",
            index=models.Index(fields=["security"], name="results_security_idx"),
        ),
        migrations.AddIndex(
            model_name="researchresults",
            index=models.Index(
                fields=["risk_score", "confidence_score"],
                name="results_scores_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="researchiteration",
            index=models.Index(
                fields=["security", "iteration_type"],
                name="iteration_security_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="researchiteration",
            index=models.Index(fields=["status"], name="iteration_status_idx"),
        ),
        migrations.AddIndex(
            model_name="researchiteration",
            index=models.Index(fields=["created_at"], name="iteration_created_idx"),
        ),
        migrations.AddIndex(
            model_name="mentalmodel",
            index=models.Index(fields=["security"], name="mental_model_security_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgereference",
            index=models.Index(fields=["security"], name="knowledge_security_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgereference",
            index=models.Index(fields=["mental_model"], name="knowledge_model_idx"),
        ),
        migrations.AddIndex(
            model_name="exclusion",
            index=models.Index(fields=["security"], name="exclusion_security_idx"),
        ),
        migrations.AddIndex(
            model_name="exclusion",
            index=models.Index(
                fields=["category", "criteria"],
                name="exclusion_category_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentreference",
            index=models.Index(fields=["security"], name="content_security_idx"),
        ),
        migrations.AddIndex(
            model_name="contentreference",
            index=models.Index(fields=["knowledge_ref"], name="content_knowledge_idx"),
        ),
        migrations.AddIndex(
            model_name="contentreference",
            index=models.Index(
                fields=["content_type", "content_id"],
                name="content_type_id_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["client"], name="activity_client_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["activity_type"], name="activity_type_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["created_at"], name="activity_date_idx"),
        ),
    ]
