# Generated by Django 5.1.5 on 2025-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0007_alter_rawemail_checksum"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
