# Generated by Django 5.1.5 on 2025-01-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0006_contacthistory_contacttag_enrichmenttask_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawemail",
            name="checksum",
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
