# Generated by Django 5.1.5 on 2025-01-17 06:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0002_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.TextField()),
                ("body", models.TextField()),
                ("sender", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "indexes": [
                    models.Index(fields=["sender"], name="message_sender_idx"),
                    models.Index(fields=["created_at"], name="message_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Thread",
                "verbose_name_plural": "Threads",
                "indexes": [
                    models.Index(fields=["created_at"], name="thread_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailLabelHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label_id", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[("ADDED", "Added"), ("REMOVED", "Removed")],
                        max_length=10,
                    ),
                ),
                ("changed_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_history",
                        to="database.email",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Label History",
                "verbose_name_plural": "Email Label Histories",
                "indexes": [
                    models.Index(fields=["email", "label_id"], name="email_label_idx"),
                    models.Index(
                        fields=["created_at"],
                        name="label_history_created_idx",
                    ),
                ],
            },
        ),
    ]
