# Generated by Django 5.1.5 on 2025-01-17 06:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0003_message_thread_emaillabelhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageThreadAssociation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_associations",
                        to="database.message",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_associations",
                        to="database.thread",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Thread Association",
                "verbose_name_plural": "Message Thread Associations",
                "indexes": [
                    models.Index(
                        fields=["message", "thread"],
                        name="message_thread_idx",
                    ),
                ],
                "unique_together": {("message", "thread")},
            },
        ),
    ]
