{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "181593a7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: duckdb in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (1.1.3)\n",
      "Requirement already satisfied: python-dotenv in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (1.0.1)\n",
      "Requirement already satisfied: google-auth-oauthlib in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (1.2.1)\n",
      "Requirement already satisfied: google-auth-httplib2 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (0.2.0)\n",
      "Requirement already satisfied: google-api-python-client in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (2.154.0)\n",
      "Requirement already satisfied: pandas in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (2.2.3)\n",
      "Requirement already satisfied: google-auth>=2.15.0 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from google-auth-oauthlib) (2.36.0)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from google-auth-oauthlib) (2.0.0)\n",
      "Requirement already satisfied: httplib2>=0.19.0 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from google-auth-httplib2) (0.22.0)\n",
      "Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from google-api-python-client) (2.23.0)\n",
      "Requirement already satisfied: uritemplate<5,>=3.0.1 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from google-api-python-client) (4.1.1)\n",
      "Requirement already satisfied: numpy>=1.26.0 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from pandas) (2.1.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from pandas) (2024.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from pandas) (2024.2)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.66.0)\n",
      "Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (5.28.3)\n",
      "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.25.0)\n",
      "Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.32.3)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (5.5.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (0.4.1)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (4.9)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from httplib2>=0.19.0->google-auth-httplib2) (3.2.0)\n",
      "Requirement already satisfied: six>=1.5 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.2.2)\n",
      "Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-auth-oauthlib) (0.6.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.4.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.26.20)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/srvo/venvs/datasci/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2024.8.30)\n",
      "Collecting tqdm\n",
      "  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)\n",
      "Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)\n",
      "Installing collected packages: tqdm\n",
      "Successfully installed tqdm-4.67.1\n"
     ]
    }
   ],
   "source": [
    "!pip install duckdb python-dotenv\n",
    "!pip install google-auth-oauthlib google-auth-httplib2 google-api-python-client pandas\n",
    "!pip install tqdm\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ca53e9c4",
   "metadata": {},
   "source": [
    "## Extract Contacts from Gmail \n",
    " - and write them to duckdb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "f6a1bfe8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Removing existing token.pickle to force new authentication...\n",
      "Starting email fetch with debug info...\n",
      "Starting authentication process...\n",
      "No valid credentials found. Starting new OAuth flow...\n",
      "Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=577261156322-focqagcj5ko0guu810a84a7equevlb3h.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A58319%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.readonly&state=YSYyqgRtvNphtYRaFHcLjDv4wT1HtP&access_type=offline\n",
      "Saved new credentials to token.pickle\n",
      "Successfully authenticated as: sloane@ethicic.com\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Writing batch of 1000 emails to database...\n",
      "Total processed so far: 1000\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Writing batch of 1000 emails to database...\n",
      "Total processed so far: 2000\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Writing batch of 1000 emails to database...\n",
      "Total processed so far: 3000\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Writing batch of 1000 emails to database...\n",
      "Total processed so far: 4000\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Writing batch of 1000 emails to database...\n",
      "Error processing message 1921e59d3134adf3: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Writing batch of 1001 emails to database...\n",
      "Error processing message 1921e58872f069eb: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1002 emails to database...\n",
      "Error processing message 1921e543119dfce9: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1003 emails to database...\n",
      "Error processing message 1921e54131300d17: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1004 emails to database...\n",
      "Error processing message 1921e4e40fe45aa7: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1005 emails to database...\n",
      "Error processing message 1921dbbf6315a25c: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1006 emails to database...\n",
      "Error processing message 1921d86aa5af3def: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1007 emails to database...\n",
      "Error processing message 1921d7d2305e8ce5: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1008 emails to database...\n",
      "Error processing message 1921d622b7d96c67: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1009 emails to database...\n",
      "Error processing message 1921d43eb8917962: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1010 emails to database...\n",
      "Error processing message 1921d415bfc28efa: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1011 emails to database...\n",
      "Error processing message 1921d36916894f29: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1012 emails to database...\n",
      "Error processing message 1921d2eb736e7ec4: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1013 emails to database...\n",
      "Error processing message 1921d1f3207bc070: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1014 emails to database...\n",
      "Error processing message 1921cc5ddb60f1cf: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1015 emails to database...\n",
      "Error processing message 1921c9eefe86d83a: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1016 emails to database...\n",
      "Error processing message 1921c89cde1894d5: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1017 emails to database...\n",
      "Error processing message 1921c88ba14a96a0: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1018 emails to database...\n",
      "Error processing message 1921c1c601cedd7a: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1019 emails to database...\n",
      "Error processing message 1921c07c5e57a221: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1020 emails to database...\n",
      "Error processing message 1921bedfe0440739: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1021 emails to database...\n",
      "Error processing message 1921bd1b1fbc031f: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1022 emails to database...\n",
      "Error processing message 1921b3896a50ebf5: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1023 emails to database...\n",
      "Error processing message 1921b35020834fac: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1024 emails to database...\n",
      "Error processing message 1921b1ca1148a2c9: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1025 emails to database...\n",
      "Error processing message 1921aee77d09c592: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1026 emails to database...\n",
      "Error processing message 1921aed42c0e59d8: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1027 emails to database...\n",
      "Error processing message 1921ae3c4a3bbb48: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1028 emails to database...\n",
      "Error processing message 1921ac941c77fd7f: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1029 emails to database...\n",
      "Error processing message 1921a9259bc82f50: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1030 emails to database...\n",
      "Error processing message 1921a8ccf2004981: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1031 emails to database...\n",
      "Error processing message 1921a8488580cfa2: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1032 emails to database...\n",
      "Error processing message 1921a7707381dc2b: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1033 emails to database...\n",
      "Error processing message 1921a7484c0e3ad8: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1034 emails to database...\n",
      "Error processing message 1921a7447d7d56a9: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1035 emails to database...\n",
      "Error processing message 1921a73fdfa3931b: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1036 emails to database...\n",
      "Error processing message 1921a422a92e43eb: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1037 emails to database...\n",
      "Error processing message 1921a1d4d7bc78ec: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1038 emails to database...\n",
      "Error processing message 1921a0bd1b569517: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1039 emails to database...\n",
      "Error processing message 1921a0ae78f23aa5: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1040 emails to database...\n",
      "Error processing message 19219f5126b00d95: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1041 emails to database...\n",
      "Error processing message 19219a4b6ec8f27f: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1042 emails to database...\n",
      "Error processing message 192196b94cf1a945: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1043 emails to database...\n",
      "Error processing message 19219316144bea91: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1044 emails to database...\n",
      "Error processing message 19217f82a1652479: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1045 emails to database...\n",
      "Error processing message 19217ac21434a36a: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1046 emails to database...\n",
      "Error processing message 19216c3698a6207b: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1047 emails to database...\n",
      "Error processing message 19216aba0e6a0399: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1048 emails to database...\n",
      "Error processing message 192168e5f0002226: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1049 emails to database...\n",
      "Error processing message 1921672dc8905d85: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1050 emails to database...\n",
      "Error processing message 1921664fed1a5057: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1051 emails to database...\n",
      "Error processing message 1921664c2d519e0e: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1052 emails to database...\n",
      "Error processing message 192166483e9afd08: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1053 emails to database...\n",
      "Error processing message 19216647520bfbcf: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1054 emails to database...\n",
      "Error processing message 19216640b94d5462: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1055 emails to database...\n",
      "Error processing message 1921663938d4a4d5: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1056 emails to database...\n",
      "Error processing message 19215f552513f10f: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1057 emails to database...\n",
      "Error processing message 19215ce5fbb0aac2: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1058 emails to database...\n",
      "Error processing message 19215bab95429971: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1059 emails to database...\n",
      "Error processing message 1921594396089717: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1060 emails to database...\n",
      "Error processing message 192152f7c9272100: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1061 emails to database...\n",
      "Error processing message 19214e5921069673: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1062 emails to database...\n",
      "Error processing message 19214b13f1561ad1: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1063 emails to database...\n",
      "Error processing message 19214841731b5911: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1064 emails to database...\n",
      "Error processing message 192145e9227e3161: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1065 emails to database...\n",
      "Error processing message 192144db01eeb348: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1066 emails to database...\n",
      "Error processing message 1921408139ecd9d4: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1067 emails to database...\n",
      "Error processing message 192137a2052c9f60: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1068 emails to database...\n",
      "Error processing message 1921362264f915c9: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1069 emails to database...\n",
      "Error processing message 192135991b156f5c: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1070 emails to database...\n",
      "Error processing message 192133626ed60276: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1071 emails to database...\n",
      "Error processing message 19212d4293851773: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1072 emails to database...\n",
      "Error processing message 1921251134ad1556: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1073 emails to database...\n",
      "Error processing message 19211fd7915ef747: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1074 emails to database...\n",
      "Error processing message 19211f0b05dc431c: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1075 emails to database...\n",
      "Error processing message 19211e84dcba3a02: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1076 emails to database...\n",
      "Error processing message 19211e637d179032: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1077 emails to database...\n",
      "Error processing message 19211bbdb3f5eade: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1078 emails to database...\n",
      "Error processing message 1921197935abdb9b: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1079 emails to database...\n",
      "Error processing message 1921195147abee43: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1080 emails to database...\n",
      "Error processing message 1921193b2b86318a: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1081 emails to database...\n",
      "Error processing message 192118e3120e4f4e: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1082 emails to database...\n",
      "Error processing message 192116b374cf0d9a: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1083 emails to database...\n",
      "Error processing message 192116933c6005e5: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1084 emails to database...\n",
      "Error processing message 1921146c5ff49aa8: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1085 emails to database...\n",
      "Error processing message 192112cbc9b1f598: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1086 emails to database...\n",
      "Error processing message 1921112f3f1b1651: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1087 emails to database...\n",
      "Error processing message 192110e35ff0b51c: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1088 emails to database...\n",
      "Error processing message 19210f772ca65449: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1089 emails to database...\n",
      "Error processing message 19210f772b0ce72e: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1090 emails to database...\n",
      "Error processing message 19210e9e8b4dab9c: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1091 emails to database...\n",
      "Error processing message 19210e7d8db3570c: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1092 emails to database...\n",
      "Error processing message 19210e165ed39d2a: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1093 emails to database...\n",
      "Error processing message 19210e163307b626: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1094 emails to database...\n",
      "Error processing message 19210da5cb995ea4: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1095 emails to database...\n",
      "Error processing message 19210d49df03adae: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1096 emails to database...\n",
      "Error processing message 19210d4217e33d18: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1097 emails to database...\n",
      "Error processing message 19210d126eb02b55: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1098 emails to database...\n",
      "Error processing message 19210cf8446577d4: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1099 emails to database...\n",
      "Error processing message 19210cc57dc6675e: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1100 emails to database...\n",
      "Error processing message 19210cbea2e4d933: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Processing batch of 100 messages...\n",
      "\n",
      "Writing batch of 1101 emails to database...\n",
      "Error processing message 19210cb86aa10657: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1102 emails to database...\n",
      "Error processing message 19210caf5e2a4568: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1103 emails to database...\n",
      "Error processing message 19210ba80afcbf86: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Contents/MacOS/dbeaver (PID 5402) by user srvo. See also https://duckdb.org/docs/connect/concurrency\n",
      "\n",
      "Writing batch of 1104 emails to database...\n",
      "Error processing message 19210996df45db25: IO Error: Could not set lock on file \"/Users/srvo/Development/.ipynb_checkpoints/emails.duckdb\": Conflicting lock is held in /Applications/DBeaver.app/Co