"""Django database migrations package.

This package contains database migration files that track and apply
changes to the database schema over time. Each migration file represents
a specific set of schema changes that can be applied or rolled back.

Migrations are automatically generated by Django when models change and
are used to keep the database schema in sync with the models.
"""
