# Generated by Django 5.1.5 on 2025-01-17 22:05

from django.db import migrations, models


def alter_field_metadata(apps, schema_editor, model_name: str) -> None:
    """Alters the metadata field of a given model to allow null and blank values."""
    migrations.AlterField(
        model_name=model_name,
        name="metadata",
        field=models.JSONField(blank=True, null=True),
    )


def alter_field_result(apps, schema_editor) -> None:
    """Alters the result field of EnrichmentTask to allow null and blank values."""
    migrations.AlterField(
        model_name="enrichmenttask",
        name="result",
        field=models.JSONField(blank=True, null=True),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("email_processing", "0002_contact_enrichmentsource_enrichmenttask_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enrichmenttask",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enrichmenttask",
            name="result",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
