# Generated by Django 5.1.5 on 2025-01-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0004_messagethreadassociation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["name"],
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.RemoveField(
            model_name="contact",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="last_name",
        ),
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="email",
            name="labels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="email",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventlog",
            name="performed_by",
            field=models.CharField(blank=True, default="system", max_length=255),
        ),
        migrations.AddField(
            model_name="rawemail",
            name="checksum",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
