repos:
- repo: local
  hooks:
    - id: legacy-refactor
      name: Legacy Code Refactor
      entry: python src/dewey/scripts/legacy_refactor.py
      language: system
      stages: [pre-commit]
      verbose: true
