# .pre-commit-config.yaml


# Optional: Specify minimum pre-commit version
# default_language_version:
#   python: python3.12

repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies: [mdformat-myst]
        files: ^docs/.*\.md$

  # Standard hooks provided by pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest stable version
    hooks:
      - id: trailing-whitespace
        fail_fast: true
        verbose: true
      - id: end-of-file-fixer
        fail_fast: true
        verbose: true
      - id: check-yaml
        verbose: true
      - id: check-json
        verbose: true
      - id: check-added-large-files
        verbose: true
      - id: detect-private-key
        verbose: true
      - id: check-merge-conflict
        verbose: true
      - id: no-commit-to-branch
        args: [--branch, main]
        verbose: true
      - id: mixed-line-ending
        args: [--fix=lf]
        verbose: true

  # Add indentation checker - must run BEFORE other Python formatters
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ["--ignore=D203"]  # Only ignore D203 (conflicts with D211)
        additional_dependencies: [tomli]
        exclude: >
          (?x)^(
            scripts/extract_non_compliant\.py|
            scripts/find_non_compliant\.py|
            scripts/fix_backticks\.py|
            scripts/migrate_script_init\.py|
            scripts/update_compliance\.py|
            src/dewey/core/research/analysis/controversy_analyzer\.py|
            src/dewey/core/research/analysis/financial_analysis\.py|
            src/dewey/core/research/companies/companies\.py|
            src/dewey/core/research/json_research_integration\.py|
            src/dewey/core/research/port/tic_delta_workflow\.py|
            src/dewey/core/research/workflows/ethical\.py|
            src/dewey/llm/agents/docstring_agent\.py|
            src/ui/ethifinx/exceptions_8201d6dc\.py|
            src/ui/ethifinx/research/tests/test_search_workflow_a80fabda\.py|
            src/ui/ethifinx/utils_29150819\.py|
            src/ui/screens/crm_screen\.py|
            tests/.*
          )
        verbose: true

  # Custom local hooks
  - repo: local
    hooks:
      - id: check-abstract-methods
        name: Check required abstract methods implementation
        entry: python scripts/check_abstract_methods.py
        language: python
        types: [python]
        exclude: >
          (?x)^(
            tests/.*
          )
        verbose: true
      - id: fix-docstrings
        name: Fix docstring formatting issues
        entry: python scripts/fix_docstrings.py
        language: python
        types: [python]
        pass_filenames: true
        verbose: true
        description: "Automatically formats docstrings according to PEP 257 conventions"

  # Ruff - Linter and Formatter (super fast, replaces flake8, isort, black etc.)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4 # Use the latest stable version
    hooks:
      # Run the linter with comprehensive checks
      - id: ruff
        args:
          - --fix  # Re-enable auto-fixing for safe fixes
          - --preview  # Enable preview mode for unstable rules
          - --select=ALL  # Enable all error codes
          - --ignore=E501  # Line too long (handled by formatter)
          - --ignore=E203  # Whitespace before colon (conflicts with black)
          - --ignore=D203  # 1 blank line required before class docstring (conflicts with D211)
          - --ignore=D212  # Multi-line docstring summary should start at first line (conflicts with D213)
          - --show-source  # Show source code context
          - --show-fixes  # Show what fixes would be applied
        fail_fast: true
        verbose: true
        # Exclude files in gitignore
        exclude: >
          (?x)^(
            __pycache__/|\.git/|\.venv/|venv/|\.env|logs/|\.aider|
            .*\.duckdb|.*\.duckdb\.wal|backups/|
            .*_token\.json|.*_credentials\.json|.*_secret\.|secrets/|.*_key\.txt|
            scripts/extract_non_compliant\.py|scripts/find_non_compliant\.py|
            scripts/fix_backticks\.py|scripts/migrate_script_init\.py|
            scripts/update_compliance\.py|
            src/dewey/core/research/analysis/controversy_analyzer\.py|
            src/dewey/core/research/analysis/financial_analysis\.py|
            src/dewey/core/research/companies/companies\.py|
            src/dewey/core/research/json_research_integration\.py|
            src/dewey/core/research/port/tic_delta_workflow\.py|
            src/dewey/core/research/workflows/ethical\.py|
            src/dewey/llm/agents/docstring_agent\.py|
            src/ui/ethifinx/exceptions_8201d6dc\.py|
            src/ui/ethifinx/research/tests/test_search_workflow_a80fabda\.py|
            src/ui/ethifinx/utils_29150819\.py|
            src/ui/screens/crm_screen\.py
          )$
      # Run the formatter (replaces black)
      - id: ruff-format
        fail_fast: true
        verbose: true
        exclude: >
          (?x)^(
            __pycache__/|\.git/|\.venv/|venv/|\.env|logs/|\.aider|
            .*\.duckdb|.*\.duckdb\.wal|backups/|
            .*_token\.json|.*_credentials\.json|.*_secret\.|secrets/|.*_key\.txt|
            scripts/extract_non_compliant\.py|scripts/find_non_compliant\.py|
            scripts/fix_backticks\.py|scripts/migrate_script_init\.py|
            scripts/update_compliance\.py|
            src/dewey/core/research/analysis/controversy_analyzer\.py|
            src/dewey/core/research/analysis/financial_analysis\.py|
            src/dewey/core/research/companies/companies\.py|
            src/dewey/core/research/json_research_integration\.py|
            src/dewey/core/research/port/tic_delta_workflow\.py|
            src/dewey/core/research/workflows/ethical\.py|
            src/dewey/llm/agents/docstring_agent\.py|
            src/ui/ethifinx/exceptions_8201d6dc\.py|
            src/ui/ethifinx/research/tests/test_search_workflow_a80fabda\.py|
            src/ui/ethifinx/utils_29150819\.py|
            src/ui/screens/crm_screen\.py
          )$

  # Pyupgrade - Upgrades Python syntax to newer versions
  # This needs to run AFTER indentation issues are fixed
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2 # Use the latest stable version
    hooks:
      - id: pyupgrade
        args: [--py312-plus] # Target Python 3.12 or newer syntax
        exclude: |
          (?x)(
            ^.*\b(tests|test_)\b.*$|  # Skip test files which might have special syntax
            scripts/extract_non_compliant\.py|
            scripts/find_non_compliant\.py|
            scripts/fix_backticks\.py|
            scripts/migrate_script_init\.py|
            scripts/update_compliance\.py|
            src/dewey/core/research/analysis/controversy_analyzer\.py|
            src/dewey/core/research/analysis/financial_analysis\.py|
            src/dewey/core/research/companies/companies\.py|
            src/dewey/core/research/json_research_integration\.py|
            src/dewey/core/research/port/tic_delta_workflow\.py|
            src/dewey/core/research/workflows/ethical\.py|
            src/dewey/llm/agents/docstring_agent\.py|
            src/ui/ethifinx/exceptions_8201d6dc\.py|
            src/ui/ethifinx/research/tests/test_search_workflow_a80fabda\.py|
            src/ui/ethifinx/utils_29150819\.py|
            src/ui/screens/crm_screen\.py
          )
        verbose: true

  # Add a final check for remaining Python syntax errors
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast  # Verify Python files parse as valid AST
        verbose: true

# Configure Ruff further via pyproject.toml
# [tool.ruff]
# line-length = 88
# target-version = "py312"
#
# [tool.ruff.lint]
# select = ["E", "F", "W", "I", "UP", "B", "C4"] # Example rule selection
# ignore = []
#
# [tool.ruff.format]
# quote-style = "double"
