[project]
name = "dewey"
version = "0.1.0"
description = "Data unification and analysis framework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ibis-framework",
    "duckdb",
    "python-dotenv",
    "ruff",
    "pytest",
    "ibis", # Explicit DuckDB backend
    "requests", # For API interactions
    "pyyaml", # Config file handling # Add OpenAI requirement for DeepInfra compatibility
    "openai>=1.0.0",
    "google-generativeai",
]

    "requests",
    "datetime",
    "sqlalchemy",
    "api_clients",
    "pyyaml",
    "csv",
    "uvicorn",
    "setuptools",
    "joblib",
    "pandas",
    "click",
    "pytest-mock",
    "pytest-cov",
    "boto3",
    "duckduckgo-search",
    "ratelimit",
    "botocore",
    "duckdb-engine",
    "nextcloud_client",
    "sys",
    "types",
    "ibis-framework[duckdb]",
    "config",
    "autopep8",
    "poetry",
    "SQLAlchemy",
    "psycopg2-binary",
    "scripts.enrich_contacts",
    "scripts.log_analyzer",
    "coverage",
    "aider-chat",
    "random",
    "ulid-py",
    "asgiref",
    "ulid",
    ".models.metrics",
    "..base",
    "..agents.rag",
    "..agents.ghostwriter",
    "..agents.client_advocate",
    "..agents.adversarial",
    "email_processing.prioritization.priority_rules",
    ".chat_history",
    "...models",
    "ast",
    "base",
    "syzygy[base]",
    "asyncpg",
    "..config",

    "pydantic",
    "structlog",