[project]
name = "dewey"
version = "0.1.0"
description = "Data unification and analysis framework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ibis-framework[duckdb]",
    "duckdb-engine",
    "python-dotenv",
    "ruff",
    "pytest",
    "requests",
    "pyyaml",
    "openai>=1.0.0",
    "google-generativeai",
    "pydantic",
    "structlog",
    "sqlalchemy",
    "uvicorn",
    "setuptools",
    "joblib",
    "pandas",
    "click",
    "pytest-mock",
    "pytest-cov",
    "boto3",
    "duckduckgo-search",
    "ratelimit",
    "botocore",
    "psycopg2-binary",
    "coverage",
    "ulid-py",
    "asgiref",
    "asyncpg",
    "tomli-w"  # For proper TOML handling
]

    "csv",
    "subprocess",
    "sys",
    "shutil",
    "datetime",
    "pathlib",
    "logging",
    "colorlog",
    "dotenv",
    "typing",
    "hashlib",
    "collections",
    "re",
    "json",
    "python-dateutil",
    "os",
    "argparse",
    "prometheus_client",
    "data_validator",
    "classification_engine",
    "journal_writer",
    "bin.mercury_api",
    "src.utils.errors",
    "bin.logging_config",
    "hledger",
    "prompt_toolkit",
    "duckdb",
    "deepinfra_client",
    "time",
    "dataclasses",
    "fnmatch",
    "textual",
    "fabric",
    "service_manager",
    "unittest",
    "unittest.mock",
    "PyYAML",
    "tempfile",
    ".models",
    "asyncio",
    "contextlib",
    "yaml",
    "service_manager.core",
    "service_manager.models",
    "paramiko",
    "anytree",
    "email",
    "email_validator",
    "icalendar",
    "imaplib",
    "sqlite3",
    "mailparser",
    "config",