[project]
name = "dewey"
version = "0.1.0"
description = "Data unification and analysis framework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ibis-framework",
    "duckdb",
    "python-dotenv",
    "ruff",
    "pytest",
    "ibis-duckdb",  # Explicit DuckDB backend
    "requests",      # For API interactions
    "pyyaml",        # Config file handling
    "openai>=1.0.0"  # Add OpenAI requirement for DeepInfra compatibility
]
