[project]
name = "dewey"
version = "0.1.0"
description = "Data unification and analysis framework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ibis-framework[duckdb]",
    "duckdb-engine",
    "python-dotenv>=1.0.0",
    "ruff",
    "pytest",
    "requests",
    "pyyaml>=6.0.0",
    "openai>=1.0.0",
    "google-generativeai",
    "pydantic",
    "structlog",
    "sqlalchemy",
    "uvicorn",
    "setuptools",
    "joblib",
    "pandas",
    "click",
    "pytest-mock",
    "pytest-cov",
    "boto3",
    "duckduckgo-search",
    "ratelimit",
    "botocore",
    "psycopg2-binary",
    "coverage",
    "ulid-py",
    "asgiref",
    "asyncpg",
    "tomli-w", # For proper TOML handling # Required for OpenRouter client
    "httpx",
    "tqdm",
    "flake8",
    "google-generativeai",
    "openai",
    "humanize",
    "spacy>=3.8.4",
    "black>=25.1.0",
    "numpy==1.26.0",  # Pinned for spaCy compatibility
    "chromadb",
    "sentence-transformers",
    "typer>=0.9.0",
    "rich>=13.0.0",
    "sqlite3",
    "pyyaml>=6.0.0",
    "python-dotenv",
    "pre-commit",
    "ruff",
]

[tool.setuptools]
package-dir = {"" = "src"}
