site_name: Dewey
docs_dir: docs
site_url: https://srvo.github.io/dewey/dewey/
repo_url: https://github.com/srvo/dewey
repo_name: srvo/dewey

theme:
  name: material
  custom_dir: ../../templates/themes/custom
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
    - navigation.top
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Raleway
    code: Raleway
    
nav:
    - Home: index.md
    - Getting Started:
        - Installation: getting-started/installation.md
        - Quick Start Guide: getting-started/quick-start.md
        - Core Concepts: concepts/architecture.md
    - Architecture & Design:
        - System Architecture: concepts/architecture.md
        - Design Decisions:
            - ADR-0001 Database Refactor: concepts/ADRs/0001-database-operations-refactor.md
            - ADR-0002 Script Consolidation: concepts/ADRs/0002-script-consolidation.md
            - ADR-0003 Event System: concepts/ADRs/0003-module-decoupling-event-system.md
        - Core APIs:
            - Database API: reference/core_apis/database.md
            - BaseScript API: reference/core_apis/base_script.md
    - Components:
        - Base Script: components/base_script.md
        - Database: database/database.md
        - LLM Integration: components/llm.md
        - UI Components: components/ui.md
        - Automation: components/automation.md
        - Bookkeeping: components/bookkeeping.md
        - CRM: components/crm.md
        - Research: components/research.md
        - Process Feedback: components/process_feedback.md
        - Testing: components/tests.md
    - Developer Guide:
        - Contributing Guidelines: contributing/CONVENTIONS.md
        - Code Style: contributing/code_style.md
    - Tools & Utilities:
        - Dual-Model Code Quality: aider_dual_model.md
    - "It's Keynes, Stupid!":
        - Introduction: keynes/introduction.md
        - About the Author: keynes/about-the-author.md
        - Economics Fundamentals:
            - The Language of Economics: keynes/fundamentals/language-of-economics.md
            - Supply and Demand: keynes/fundamentals/supply-and-demand.md
            - Money and Banking: keynes/fundamentals/money-and-banking.md
        - Economic Policy:
            - Fiscal and Monetary Policy: keynes/policy/fiscal-monetary.md
            - Business and Government: keynes/policy/business-government.md
            - Global Economic Issues: keynes/policy/global-issues.md
        - Personal Finance:
            - Budgeting and Planning: keynes/personal/budgeting.md
            - Investment Principles: keynes/personal/investing.md
        - Economics Education:
            - Economics Syllabus: keynes/education/syllabus.md
            - Teaching Resources: keynes/education/teaching-resources.md
    - TODO: TODO.md

markdown_extensions:
    - pymdownx.betterem:
          smart_enable: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.6.0/mermaid.min.js

plugins:
    - mkdocstrings:
          default_handler: python
          handlers:
              python:
                  options:
                      docstring_style: google
    - mermaid2
    - autorefs
    - search

extra_css:
    - ../../templates/assets/stylesheets/extra.css