# Generated by Django 5.1.5 on 2025-01-17 21:06


from django.db import migrations, models
from django.db.models import Index, deletion


def create_email_model() -> models.Model:
    """Creates the Email model."""
    return models.CreateModel(
        name="Email",
        fields=[
            (
                "id",
                models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name="ID",
                ),
            ),
            ("message_id", models.CharField(max_length=255, unique=True)),
            ("subject", models.CharField(blank=True, max_length=255)),
            ("from_email", models.EmailField(max_length=254)),
            ("from_name", models.CharField(blank=True, max_length=255)),
            ("to_emails", models.JSONField(default=list)),
            ("cc_emails", models.JSONField(blank=True, default=list)),
            ("bcc_emails", models.JSONField(blank=True, default=list)),
            ("body_text", models.TextField(blank=True)),
            ("body_html", models.TextField(blank=True)),
            ("received_at", models.DateTimeField()),
            ("is_read", models.BooleanField(default=False)),
            ("is_deleted", models.BooleanField(default=False)),
            ("last_sync_at", models.DateTimeField(auto_now=True)),
        ],
        options={
            "indexes": [
                Index(fields=["message_id"], name="email_proce_message_1234ab_idx"),
                Index(fields=["from_email"], name="email_proce_from_em_5678cd_idx"),
                Index(fields=["received_at"], name="email_proce_receive_90efgh_idx"),
            ],
        },
    )


def create_raw_email_model() -> models.Model:
    """Creates the RawEmail model."""
    return models.CreateModel(
        name="RawEmail",
        fields=[
            (
                "id",
                models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name="ID",
                ),
            ),
            ("raw_data", models.BinaryField()),
            ("processed_at", models.DateTimeField(auto_now_add=True)),
            (
                "email",
                models.OneToOneField(
                    on_delete=deletion.CASCADE,
                    related_name="raw_email",
                    to="email_processing.email",
                ),
            ),
        ],
        options={
            "indexes": [
                Index(fields=["processed_at"], name="email_proce_process_ijklmn_idx"),
            ],
        },
    )


class Migration(migrations.Migration):
    """Migration class for email_processing app."""

    initial: bool = True

    dependencies: list[tuple] = []

    operations: list[models.Model] = [
        create_email_model(),
        create_raw_email_model(),
    ]
