# Suggested additions to dewey.yaml

paths:
  : /
  all holdings - 20250319_csv: /Users/srvo/Downloads/All Holdings - 20250319.csv
  client intake questionnaire (responses) - form responses 1_csv: /Users/srvo/Downloads/Client Intake Questionnaire (Responses) - Form Responses 1.csv
  households - 20250319_csv: /Users/srvo/Downloads/Households - 20250319.csv
  list for sloane_xlsx - fod v5_csv: /Users/srvo/Downloads/List for Sloane.xlsx - FOD V5.csv
  open accounts - 20250319_csv: /Users/srvo/Downloads/Open Accounts - 20250319.csv
  contributions-2025_csv: /Users/srvo/Downloads/contributions-2025.csv
  mercury_import_log: /Users/srvo/books/logs/mercury_import.log
  dewey: /Users/srvo/dewey
  conventions_md: /Users/srvo/dewey/CONVENTIONS.md
  dewey_yaml: /Users/srvo/dewey/config/dewey.yaml
  prd: /Users/srvo/dewey/config/prd
  codebase_analysis_md: /Users/srvo/dewey/docs/codebase_analysis.md
  ethifinx: /Users/srvo/ethifinx
  input_data: /Users/srvo/input_data
  activedata: /Users/srvo/input_data/ActiveData
  ria schwab_xlsx - standard template_csv: /Users/srvo/input_data/csv_files/RIA Schwab.xlsx - Standard Template.csv
  forminator-onboarding-form-241114090152_csv: /Users/srvo/input_data/csv_files/forminator-onboarding-form-241114090152.csv
  legitimate_onboarding_form_responses_csv: /Users/srvo/input_data/csv_files/legitimate_onboarding_form_responses.csv
  onboarding_responses_csv: /Users/srvo/input_data/csv_files/onboarding_responses.csv
  port_duckdb: /Users/srvo/input_data/port.duckdb
  db: /Users/srvo/lake/ethifinx/db
  feedback_json: /Users/srvo/lake/read/feedback.json
  ecic_duckdb: /Users/srvo/local/data/ecic.duckdb
  logs: /Users/srvo/local/logs
  chat: /chat
  completions: /chat/completions
  contents: /contents
  : /contents/
  _coverage: /contents/.coverage
  email_classifier_duckdb: /email_classifier.duckdb
  issues?state=closed&per_page=1: /issues?state=closed&per_page=1
  : /logs/
  process_feedback_duckdb: /process_feedback.duckdb
  search: /search
  dewey: /src/dewey
  commit_activity: /stats/commit_activity
  company_analysis_db: /var/lib/dokku/data/storage/farfalle/company_analysis.db
  _env: ~/crm/.env
  dewey: ~/dewey
  classification_rules_json: ~/dewey/config/classification_rules.json
  contact: ~/dewey/config/contact
  dewey_yaml: ~/dewey/config/dewey.yaml
  email: ~/dewey/config/email
  opportunity: ~/dewey/config/opportunity
  journals: ~/dewey/data/journals
  dewey_emails_duckdb: ~/dewey_emails.duckdb
  dewey_test_duckdb: ~/dewey_test.duckdb

settings:
  page_token: None
