# Dewey Configuration

core:
  logging:
    level: INFO
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
    file: ${LOG_FILE:-logs/dewey.log}
    retention: 30  # days

  database:
    type: postgres  # Indicates we're using PostgreSQL
    postgres:
      host: localhost
      port: 5432
      dbname: dewey_db
      user: srvo
      password: ${DB_PASSWORD}
      sslmode: prefer
      # Connection pool settings
      pool_min: 5
      pool_max: 10
      # Retry settings
      connect_timeout: 10
      keepalives_idle: 30
      max_retries: 3
      retry_delay: 1

    # Backup settings
    backup:
      enabled: true
      directory: ${BACKUP_DIR:-backups}
      retention_days: 30
      schedule: "0 2 * * *"  # Cron expression for daily backup at 2 AM

llm:
  provider: openai  # or anthropic, claude, etc.
  model: gpt-3.5-turbo
  api_key: ${OPENAI_API_KEY}
  timeout: 60
  max_tokens: 2000
  temperature: 0.7

pipelines:
  data_processing:
    batch_size: 100
    timeout: 300
    concurrent_workers: 4

# Application-specific settings
app:
  server:
    host: 0.0.0.0
    port: 8000
    debug: ${DEBUG:-false}

  ui:
    theme: light
    language: en
    refresh_interval: 60  # seconds

# Module-specific configurations
modules:
  crm:
    enabled: true
    sync_interval: 3600  # seconds
    max_contacts: 10000

  bookkeeping:
    enabled: true
    tax_rate: 0.07
    currency: USD
    fiscal_year_start: "01-01"
