---
prd:
  base_path: "config/prd"
  active_prd: "current_prd.yaml"
  schema:
    components:
      - name: str
        purpose: str
        dependencies: list[str]
        interfaces: list[str]
    decisions:
      - timestamp: datetime
        description: str
        alternatives: list[str]
        rationale: str
    conventions_ref: "../.aider/CONVENTIONS.md"
    codebase_insights_ref: "../docs/codebase_analysis.md"
