---
project_root: "src/dewey"

module_paths:
    core: "core/"
    llm: "llm/"
    pipeline: "pipeline/"
    ui: "ui/"
    utils: "utils/"
    accounting: "core/accounting/"
    research: "core/research/"
    investment_performance: "core/research/investment_performance/"

file_patterns:
    - '\.py$'
    - '\.ipynb$'

exclude_patterns:
    - '\.venv/'
    - '/venv/'
    - 'site-packages/'

llm_settings:
    models:
      - "gemini-2.0-flash"
      - "gemini-1.5-pro" 
      - "gemini-1.0-pro"
      - "gemini-1.5-flash-latest"
    temperature: 0.3
    max_retries_per_model: 2
    cooldown_minutes: 5  # Cool-down time for rate limited models
