-- Create Institutional_prospects table based on the structure of "RIA Schwab.xlsx - Standard Template.csv"
CREATE TABLE IF NOT EXISTS institutional_prospects (
    ria_firm_crd INTEGER, -- Unique identifier (CRD number)
    ria_firm_name TEXT,
    main_office_address_1 TEXT,
    main_office_address_2 TEXT,
    main_office_city TEXT,
    main_office_state TEXT,
    main_office_zip_code TEXT,
    main_office_zip_code_plus_4 TEXT,
    main_office_county TEXT,
    main_office_metropolitan_area TEXT,
    main_office_usps_certified TEXT,
    main_office_phone TEXT,
    main_office_phone_do_not_call TEXT,
    main_office_phone_type TEXT,
    num_advisory_reps DOUBLE,
    num_bd_reps DOUBLE,
    num_insurance_licensed_reps DOUBLE,
    num_employees DOUBLE,
    registration_date DATE,
    date_adv_last_amended DATE,
    total_assets_mil DOUBLE,
    total_assets_mil_separately_managed DOUBLE,
    total_assets_mil_pooled_vehicles DOUBLE,
    allocation_separately_managed_accounts DOUBLE,
    allocation_pooled_vehicles DOUBLE,
    aum_growth_rate_1_year DOUBLE,
    aum_growth_rate_5_years DOUBLE,
    average_account_size DOUBLE,
    ownership_type TEXT,
    dually_registered_bd_ria_firm TEXT,
    ria_type_retail TEXT,
    ria_type_institutional TEXT,
    investment_strategies_builds_portfolios_mutual_funds TEXT,
    investments_mutual_funds TEXT,
    assets_mil_mutual_funds DOUBLE,
    percent_assets_mutual_funds DOUBLE,
    investment_strategies_builds_portfolios_etfs_etns TEXT,
    investments_etfs TEXT,
    assets_mil_equity_exchange_traded DOUBLE,
    percent_assets_equity_exchange_traded DOUBLE,
    assets_mil_private_funds DOUBLE,
    percent_assets_private_funds DOUBLE,
    custodian_assets_mil_fidelity_nationalfinancial DOUBLE,
    custodian_assets_mil_pershing DOUBLE,
    custodian_assets_mil_schwab DOUBLE,
    custodian_assets_mil_td_ameritrade DOUBLE,
    custodian_assets_mil_interactive_brokers DOUBLE,
    q4_total_assets_mil_2015 DOUBLE,
    q4_total_assets_mil_2016 DOUBLE,
    q4_total_assets_mil_2017 DOUBLE,
    q4_total_assets_mil_2018 DOUBLE,
    q4_total_assets_mil_2019 DOUBLE,
    q4_total_assets_mil_2020 DOUBLE,
    q4_total_assets_mil_2021 DOUBLE,
    q4_total_assets_mil_2022 DOUBLE,
    firm_website TEXT,
    linkedin TEXT,
    youtube TEXT,
    twitter TEXT,
    facebook TEXT,
    discovery_data_profile_url TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index on key fields
CREATE INDEX IF NOT EXISTS idx_institutional_prospects_crd ON institutional_prospects(ria_firm_crd);
CREATE INDEX IF NOT EXISTS idx_institutional_prospects_name ON institutional_prospects(ria_firm_name);

-- Comment to explain the table's purpose
COMMENT ON TABLE institutional_prospects IS 'Table containing RIA (Registered Investment Advisor) firm data for institutional prospecting, sourced from Schwab database'; 